---
- name: Make a backup of current Oracle DB files (/ filesystem)
  archive:
    path: 
      - /u02
      - /u03
      - /u04
      - /orabackup
    dest: /root/DBarchive.tgz

- name: Delete files to free up space on /
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /u02
    - /u03
    - /u04
    - /orabackup

