---
# defaults file for wildfly
staging_folder: /opt/staging/wildfly

wildfly_version: 8.1.0
wildfly_user: jboss
wildfly_group: jboss
wildfly_home: /opt/wildfly

wildfly_mgt_user: admin
wildfly_mgt_password: admin

wildfly_app_user: wildflyappuser
wildfly_app_password: wildflyappuser
# echo -n "wildflyappuser"|base64
wildfly_app_password_base64: d2lsZGZseWFwcHVzZXI=

wildfly_bind_address: 0.0.0.0
wildfly_bind_address_management: 0.0.0.0
wildfly_management_http_port: 9990
wildfly_management_https_port: 9993
wildfly_http_port: 8080
wildfly_https_port: 8443
wildfly_ajp_port: 8009

wildfly_mail_smtp: localhost
wildfly_mail_smtp_port: 25

java_xmx: 1024m
java_xms: 512m
java_maxpermsize: 256m
java_debug: false
java_debug_port: 8787

jdbc_driver: false
wildfly_module_sstwa: false