---
- name: Get users created
  shell: "cat {{ keycloak_home }}/standalone/configuration/mgmt-users.properties | grep -v ^# | awk -F= '{print $1}'"
  register: kc_users
  ignore_errors: yes
  changed_when: no

- name: Get KEYCLOAK Administrative User
  stat:
    path: "{{keycloak_home}}/standalone/configuration/keycloak-add-user.json"
  register: keycloak_user_file

- name: Create KEYCLOAK Administrative User
  shell: "{{ keycloak_home }}/bin/add-user-keycloak.sh --sc {{ keycloak_home }}/standalone/configuration -r master -u {{ keycloak_admin_username }} -p {{ keycloak_admin_password }}"
  when: not keycloak_user_file.stat.exists

- name: Get KEYCLOAK Administrative User Definition into Ansible Server
  fetch:
    src: "{{keycloak_home}}/standalone/configuration/keycloak-add-user.json"
    dest: "{{ role_path }}/files/"
    flat: Yes
  changed_when: no

- name: Remove local file for administrative user
  local_action: file path={{ item }} state=absent
  with_items:
    - "{{ role_path }}/files/keycloak-add-user.json"
  become: no
  run_once: yes
