#Webapps
move-item E:\LPA\Webapps\AdapterService_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\APIService_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\DebugDocGenerator_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\DebugDocWorkflowService_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\DebugDownloadDocumentService_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\DebugHangfire_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\DebugLPADocService_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\DocDesignerNotificationService_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\DocDesignerWebApi_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\DocDesignerWebDAVServer_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\DocDesignerWeb_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\DocGenerator_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\DocGenExcelAddInService_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\DocWorkflowService_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\DownloadDocumentService_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\Hangfire_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\LPADocService_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\MarketDataServer_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\ProdDesigner_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\TranslationTool_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\WopiHost_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
move-item E:\LPA\Webapps\WorkflowService_SAN E:\LPA_Utils\OLD_INSTALLATION\Webapps\
#Services
move-item E:\LPA\services\AdInformationCacheBuilder_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\CostImportServiceEDG_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\CostImportService_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\DecisionEngineServiceReports_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\DecisionEngineService_COST_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\DecisionEngineService_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\DocumentExport_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\EdgGetService_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\EdgPushService_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\EdgUpdateService_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\KidCalculationGetService_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\KidCalculationPushService_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\LogFileCleaner_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\MDSUpdateService_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\UpdatedDocumentsReport_Poland_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\UpdatedDocumentsReport_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\WebRequester_SAN E:\LPA_Utils\OLD_INSTALLATION\services\
move-item E:\LPA\services\WorkflowMonitorService_SAN E:\LPA_Utils\OLD_INSTALLATION\services\