#Start AppPools
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"AdapterService"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"APIService"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"DebugDocGenerator"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"DebugDocWorkflowService"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"DebugDownloadDocumentService"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"DebugHangfire"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"DebugLPADocService"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"DocDesignerWebApi"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"DocGenerator"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"DocGenExcelAddInService"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"DocWorkflowService"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"DownloadDocumentService"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"Hangfire"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"LPADocService"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"MarketDataServer"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"ProdDesigner"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"TermsheetsAdapterService"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"TranslationTool"
C:\windows\system32\inetsrv\appcmd.exe start APPPOOL /apppool.name:"WorkflowService"

#Config site "Default Web Service" and start Site
C:\windows\system32\inetsrv\appcmd.exe set SITE /site.name:"Default Web Site" /bindings:"http://*:80" 
C:\windows\system32\inetsrv\appcmd.exe start site /site.name:"Default Web Site"
