---
- name: Create MySQL JDBC folder
  file: path={{ wildfly_home }}/modules/system/layers/base/com/mysql/jdbc/main state=directory owner={{ wildfly_user }} group={{ wildfly_group }}

- name: Get MySQL JDBC driver from artifactory
  get_url:
    url: "{{ artifactory_url }}/repo2-cache/mysql/mysql-connector-java/{{ jdbc_driver_version }}/mysql-connector-java-{{ jdbc_driver_version }}.jar"
    url_username: "{{ artifactory_user }}"
    url_password: "{{ artifactory_pass }}"
    dest: "{{ wildfly_home }}/modules/system/layers/base/com/mysql/jdbc/main/mysql-connector-java-{{ jdbc_driver_version }}.jar"
    timeout: 60

- name: Create MySQL JDBC module.xml
  template: src=mysql-jdbc-module.xml.j2 dest={{ wildfly_home }}/modules/system/layers/base/com/mysql/jdbc/main/module.xml owner={{ wildfly_user }} group={{ wildfly_group }}